title: âŠ¹ acequo # name of the site
author: ğ™°ğšŒğšğššğšğš˜ ğ™´ğš¡ğš # name of site's author
email: ğšŠğšŒğšğššğšğš˜ğšğš–@ğšğš–ğšŠğš’ğš•.ğšŒğš˜ğš– # email of site's author
url: ğš‘ğšğšğš™ğšœ://ğšŠğšŒğšğššğšğš˜.ğšğš’ğšğš‘ğšğš‹.ğš’ğš˜/ # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed) 
  <p> <span style="color: #FF3131; font-size: 1.2em;"ğ™¾ğš—ğš¢ğš ğš—ğšŠ-ğšŠğšŒğš‘á»¥ ğš—ğš›á»</span> <br> ğ™·ğšğš›ğš'ğšœ ğš–ğš¢ ğš˜ğš—ğš•ğš¢ ğšğš’ğš¡ğšğš ğšŠğšğšğš›ğšğšœğšœ <br> ğ–¨ ğ—†ğ–ºğ—‡ğ–ºğ—€ğ–¾ ğ—‰ğ—‹ğ—‚ğ—ğ–ºğ—ğ–¾ ğ–¾ğ—Šğ—ğ—‚ğ—ğ—’ ğ–¿ğ—ˆğ—‹ ğ–º ğ–¿ğ—‚ğ—‡ğ–ºğ—‡ğ–¼ğ—‚ğ–ºğ—… ğ—‚ğ—‡ğ—Œğ—ğ—‚ğ—ğ—ğ—ğ—‚ğ—ˆğ—‡, ğ—‹ğ—ğ—‡ ğ–º ğ—Œğ—†ğ–ºğ—…ğ—… ğ—ğ–¾ğ—‡ğ—ğ—ğ—‹ğ–¾ ğ–¼ğ—ˆğ—†ğ—‰ğ–ºğ—‡ğ—’ ğ–ºğ—‡ğ–½ ğ—Œğ—ğ—ğ–½ğ—’ ğ–¯ğ—Œğ—’ğ–¼ğ—ğ—ˆğ—…ğ—ˆğ—€ğ—’ (ğ–¬ğ–²ğ–¼) <br> ğ–ºğ—…ğ—ğ–ºğ—’ğ—Œ ğ—‚ğ—‡ğ—ğ–¾ğ—‹ğ–¾ğ—Œğ—ğ–¾ğ–½ ğ–ºğ–»ğ—ˆğ—ğ— ğ—‚ğ—‡ğ—ğ–¾ğ—Œğ—ğ—‚ğ—‡ğ—€ ğ—‚ğ—‡ ğ—€ğ—ˆğ—ˆğ–½ ğ—‰ğ—‹ğ—ˆğ—ƒğ–¾ğ–¼ğ—ğ—Œ : ğ–¿ğ–¾ğ–¾ğ—… ğ–¿ğ—‹ğ–¾ğ–¾ ğ—ğ—ˆ ğ—‹ğ–¾ğ–ºğ–¼ğ— ğ—ˆğ—ğ—! <br>  <br> > ğ–½ğ—ˆğ—‚ğ—‡ğ—€ ğ–º ğ—‹ğ–¾ğ—ğ—‹ğ–¾ğ–ºğ— ğ—Œğ—ˆğ—†ğ–¾ğ—ğ—ğ–¾ğ—‹ğ–¾ ğ—ˆğ—‡ ğ–¾ğ–ºğ—‹ğ—ğ— <br>  <br> <span style="color: #FFFFFF;"> <span style="font-size: 40px;">ï¸ â˜£ </span> </span>  <a href="https://music.youtube.com/playlist?list=PLXkLxioU1zl78xolDiPN0bJgKRUOWOehA&si=szIp-Ix7VteozFWq" style="color: #FFFFFF;">
    <span style="color: #FF3131;">  listen to my cool playlists </span> </a> <span style="color: #FFFFFF;"> <span style="font-size: 40px;">ï¸ â˜£ </span> </span> <br> <br> interest : investments, comp sec, research, philosophy, music, arts, literature, IOT, documentaries, photography, books, hiking, experiencing, learning... <br> <br> sweet hate : hedonism, apathy, <a href="/assets/badfaith.pdf" target="_blank" style="color: #FFFFFF;">this</a>, retards, all CHF pairs and Windows   <br> </p>

permalink: /:slug.html

favicon: "icons8-disco-ball-96.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: true
